apiVersion: v1
kind: page
spec:
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: TextField
          name: input
          props:
            fullWidth: true
            label: Encoded text
            defaultValue: www.mui.com
    - component: PageRow
      name: pageRow1
      children:
        - component: Image
          name: qrcodeDisplay
          props:
            src:
              $$jsExpression: |
                qrImage.data
            fit: none
  queries:
    - name: qrImage
      query:
        function: generateQrCode
        kind: local
      parameters:
        - name: content
          value:
            $$jsExpression: |
              input.value
